### ISSUE TITLE
Ambiguous method overloading for method java.io.FileReader#<init>

### ISSUE THREAD

**Issue by akomakom** [jenkinsci/matrix-groovy-execution-strategy-plugin#15]
When using an absolute filename for the script, I get the exception below.

It doesn't matter if the matrix one-off executor is the master or a slave.  
Looking at the code at https://github.com/jenkinsci/matrix-groovy-execution-strategy-plugin/blob/master/src/main/groovy/org/jenkinsci/plugins/WorkspaceFileReader.groovy#L23 I am wondering if that's caused by a typo.  Should that be 

      scriptFile = new FileReader(file)
?  Seems that scriptFile remains null.  

Exception:
```
groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.io.FileReader#<init>.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
	[class java.lang.String]
	[class java.io.File]
	[class java.io.FileDescriptor]
	at groovy.lang.MetaClassImpl.chooseMostSpecificParams(MetaClassImpl.java:3263)
	at groovy.lang.MetaClassImpl.chooseMethodInternal(MetaClassImpl.java:3216)
	at groovy.lang.MetaClassImpl.chooseMethod(MetaClassImpl.java:3159)
	at groovy.lang.MetaClassImpl.createConstructorSite(MetaClassImpl.java:3452)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:91)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.WorkspaceFileReader.<init>(WorkspaceFileReader.groovy:23)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:54)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:364)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:490)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)
```

(Jenkins 2.63, Plugin 1.0.6)

**Comment by akomakom** [comment]
I've confirmed that changing the code as I indicated yields correct behavior insofar as it causes the plugin to look for the script on the master and not on the slave.  What is the intended behavior here?  Since I see no code that deals with slave channels, I'm assuming that this is the way it should work, so I'll open a PR
