### ISSUE TITLE
Requesting the very simplest example

### ISSUE THREAD

**Issue by DavidGangel** [jenkinsci/matrix-groovy-execution-strategy-plugin#17]
Hi,

Can someone please post a very simple example of the groovy script when feeding the Axis just manually through the groovy script?
It would help to proceed forward to the real dynamic way.

Thank you!

**Comment by DavidGangel** [comment]
Hi,

I tried the most simple way by using the example on the doc:
```
combinations=[
    [ axis1: "a", axis2: "x" ],
	[ axis1: "a", axis2: "y" ],
	[ axis1: "a", axis2: "z" ],
	[ axis1: "b", axis2: "x" ],
	[ axis1: "b", axis2: "y" ],
	[ axis1: "b", axis2: "z" ]
]

println combinations

combinations.each{
	
				if(it.axis2 == 'z')
					  return
	
				result[it.axis2] = result[it.axis2] ?: []
				result[it.axis2] << it
}

println result

return [result, true]
```

Now when running the job with such a script I get NPE:
Commit message: "Trying."
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 990de8646e3d4f373c62e760b65a615d60aefd89
 > git rev-list 990de8646e3d4f373c62e760b65a615d60aefd89 # timeout=10
[[axis1:a, axis2:x], [axis1:a, axis2:y], [axis1:a, axis2:z], [axis1:b, axis2:x], [axis1:b, axis2:y], [axis1:b, axis2:z]]
[x:[[axis1:a, axis2:x], [axis1:b, axis2:x]], y:[[axis1:a, axis2:y], [axis1:b, axis2:y]]]
Set build name.
New build name is '140-LIVE'
Running x
FATAL: null
java.lang.NullPointerException

That's all in the console. There is no debug information at all.

Can someone please help to figure out what do I need to do in order to have a simple run?

Thank you.

**Comment by JeremyMarshall** [comment]
Hi
did you upgrade to the latest version? as there is a change to the latest
version to return if to continue on error or not.

try `return result` to return

Regards
Jeremy

**Comment by DavidGangel** [comment]
Hi Jeremy,

Thank you for your respond.
I got the same error when I just return with the single result.

I'm using:

Matrix Groovy Execution Strategy PluginMatrix Groovy Execution Strategy Plugin | 1.0.6

**Comment by DavidGangel** [comment]
Hi Jeremy,

If I add user defined axis with their values to the configuration, then the NPE is not happening and the job succeeds.
But the main target of this plugin shouldn't be to give the ability to define the axis diynamically without manual axis definition?
Sorry if I understand something incorrectly, then please correct me.

Thank you.

Best regards,
David Gangel

**Comment by tolland** [comment]
Yeah, I am getting something similar.;

Jenks and the plugins were installed this week, so everything is up to date. I'll try disabling other plugins etc...

```
println 'something for the log'
return [result, true]

```

> 
> 18:01:15 Started by user Tom
> 18:01:15 Building in workspace /var/lib/jenkins/workspace/multi-downstream-1
> 18:01:15 something for the log
> 18:01:15 [PostBuildScript] - Executing post build scripts.
> 18:01:15 [PostBuildScript] - Problem occurred: groovy.lang.MissingPropertyException: No such property: executable for class: hudson.model.OneOffExecutor
> 18:01:15 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
> 18:01:15 	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getProperty(ScriptBytecodeAdapter.java:458)
> 18:01:15 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:286)
> 18:01:15 	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onGetProperty(GroovyInterceptor.java:68)
> 18:01:15 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onGetProperty(SandboxInterceptor.java:312)
> 18:01:15 	at org.kohsuke.groovy.sandbox.impl.Checker$6.call(Checker.java:284)
> 18:01:15 	at org.kohsuke.groovy.sandbox.impl.Checker.checkedGetProperty(Checker.java:288)
> 18:01:15 	at org.kohsuke.groovy.sandbox.impl.Checker$checkedGetProperty$0.callStatic(Unknown Source)
> 18:01:15 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
> 18:01:15 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
> 18:01:15 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:230)
> 18:01:15 	at Script1.run(Script1.groovy:3)
> 18:01:15 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.GroovySandbox.run(GroovySandbox.java:141)
> 18:01:15 	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SecureGroovyScript.evaluate(SecureGroovyScript.java:333)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.service.GroovyScriptExecutor.call(GroovyScriptExecutor.java:56)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.service.GroovyScriptExecutor.call(GroovyScriptExecutor.java:17)
> 18:01:15 	at hudson.FilePath.act(FilePath.java:1084)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.service.GroovyScriptPreparer.evaluateScript(GroovyScriptPreparer.java:54)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.service.GroovyScriptPreparer.evaluateScript(GroovyScriptPreparer.java:40)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processGroovyScripts(Processor.java:160)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.processor.Processor.processScripts(Processor.java:97)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.processor.Processor.process(Processor.java:83)
> 18:01:15 	at org.jenkinsci.plugins.postbuildscript.ConfigurableMatrixAggregator.endBuild(ConfigurableMatrixAggregator.java:35)
> 18:01:15 	at hudson.matrix.MatrixBuild$MatrixBuildExecution.post2(MatrixBuild.java:424)
> 18:01:15 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
> 18:01:15 	at hudson.model.Run.execute(Run.java:1749)
> 18:01:15 	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:314)
> 18:01:15 	at hudson.model.ResourceController.execute(ResourceController.java:97)
> 18:01:15 	at hudson.model.Executor.run(Executor.java:429)
> 18:01:15 
> 18:01:15 Finished: FAILURE
