### ISSUE TITLE
Impossible to use a groovy script in a slave node workspace

### ISSUE THREAD

**Issue by Nicobubu** [jenkinsci/matrix-groovy-execution-strategy-plugin#19]
I use Jenkins 2.107.2 and Matrix Groovy Execution Strategy Plugin 1.07.

It's impossible to use workspace groovy script configuration when the job is executed on a slave node.

The job is a multi-configuration project, and its execution is restricted on a slave node.

If I execute the job on the master node, it's work, the plugin gets the script in the workspace, but it fails when it's executed on a slave node.

```

Started by timer
[EnvInject] - Loading node environment variables.
Building remotely on slave2 in workspace /jenkins/workspace/Test_auto
Updating svn://svnserver/validation at revision '2018-10-25T15:03:00.356 +0200'
At revision 12933

No changes for svn://svnserver/validation since the previous build
FATAL: /jenkins/workspace/Test_auto/slave_configuration.gy (No such file or directory)
java.io.FileNotFoundException: /jenkins/workspace/Test_auto/slave_configuration.gy (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at sun.reflect.GeneratedConstructorAccessor891.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.WorkspaceFileReader.<init>(WorkspaceFileReader.groovy:25)
	at sun.reflect.GeneratedConstructorAccessor887.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:83)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:105)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
	at org.jenkinsci.plugins.GroovyScriptMES.decideOrder(GroovyScriptMES.groovy:54)
	at org.jenkinsci.plugins.GroovyScriptMES$decideOrder.callCurrent(Unknown Source)
	at org.jenkinsci.plugins.BaseMES.run(BaseMES.groovy:51)
	at hudson.matrix.MatrixBuild$MatrixBuildExecution.doRun(MatrixBuild.java:375)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1727)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:323)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Started calculate disk usage of build
Finished Calculation of disk usage of build in 0 seconds
Started calculate disk usage of workspace
Finished Calculation of disk usage of workspace in 0 seconds
Finished: FAILURE

```

**Comment by lupalby** [comment]
I am also affected by this. Unfortunately I don't think we will get a fix for this, as there is no update in the repo for the past several years

**Comment by JeremyMarshall** [comment]
sorry, I don't really have any way of developing this plugin at present. I can put it up for adoption.

**Comment by lupalby** [comment]
If you can't maintain it anymore it would be very kind if you could put it up for adoption. Hopefully somebody else will be nice enough to pick up your great work from here.
